"""Inicializar esquema de base de datos

Revision ID: 7d8d99161fe9
Revises: 
Create Date: 2026-06-11 05:47:48.047716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d8d99161fe9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # SQLite no soporta DROP INDEX directamente, así que usamos IF EXISTS
    try:
        op.execute("DROP INDEX IF EXISTS ix_apscheduler_jobs_next_run_time")
    except Exception:
        pass
    try:
        op.drop_table('apscheduler_jobs')
    except Exception:
        pass
    try:
        op.drop_column('channels', 'fecha_ejecucion')
    except Exception:
        pass
    try:
        op.drop_column('channels', 'channel_name')
    except Exception:
        pass
    
    # SQLite no soporta ALTER COLUMN, necesitamos recrear la tabla prompts
    # Guardar datos existentes
    op.execute("CREATE TABLE prompts_backup AS SELECT * FROM prompts")
    op.drop_table('prompts')
    
    # Crear la nueva tabla sin NOT NULL en prompt_type
    op.create_table('prompts',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('title', sa.String(length=255), nullable=False),
        sa.Column('content', sa.Text(), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('category', sa.String(length=100), nullable=False, server_default='otro'),
        sa.Column('rating', sa.Float(), nullable=True, server_default='0.0'),
        sa.Column('usage_count', sa.Integer(), nullable=True, server_default='0'),
        sa.Column('version', sa.Integer(), nullable=True, server_default='1'),
        sa.Column('prompt_type', sa.String(length=100), nullable=True),
        sa.Column('variables', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), server_default=sa.func.current_timestamp()),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.func.current_timestamp(), onupdate=sa.func.current_timestamp()),
        sa.PrimaryKeyConstraint('id')
    )
    
    # Restaurar datos
    op.execute("""
        INSERT INTO prompts (id, title, content, description, category, rating, 
                            usage_count, version, prompt_type, variables, created_at, updated_at)
        SELECT id, title, content, description, category, rating,
               usage_count, version, prompt_type, variables, created_at, updated_at
        FROM prompts_backup
    """)
    op.drop_table('prompts_backup')
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Recrear prompts con prompt_type NOT NULL
    op.execute("CREATE TABLE prompts_backup AS SELECT * FROM prompts")
    op.drop_table('prompts')
    
    op.create_table('prompts',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('title', sa.String(length=255), nullable=False),
        sa.Column('content', sa.Text(), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('category', sa.String(length=100), nullable=False),
        sa.Column('rating', sa.Float(), nullable=True),
        sa.Column('usage_count', sa.Integer(), nullable=True),
        sa.Column('version', sa.Integer(), nullable=True),
        sa.Column('prompt_type', sa.String(length=100), nullable=False),
        sa.Column('variables', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    
    op.execute("""
        INSERT INTO prompts (id, title, content, description, category, rating,
                            usage_count, version, prompt_type, variables, created_at, updated_at)
        SELECT id, title, content, description, category, rating,
               usage_count, version, COALESCE(prompt_type, 'default'), variables, created_at, updated_at
        FROM prompts_backup
    """)
    op.drop_table('prompts_backup')
    
    op.add_column('channels', sa.Column('channel_name', sa.String(), nullable=True))
    op.add_column('channels', sa.Column('fecha_ejecucion', sa.String(), nullable=True))
    op.create_table('apscheduler_jobs',
        sa.Column('id', sa.String(length=191), nullable=False),
        sa.Column('next_run_time', sa.Float(), nullable=True),
        sa.Column('job_state', sa.BLOB(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_apscheduler_jobs_next_run_time'), 'apscheduler_jobs', ['next_run_time'], unique=False)
    # ### end Alembic commands ###
